export const ANALYSIS_RUN_API_PREFIX = '/v1/analysis-runs';

export const ANALYSIS_REQUEST_SUCCESS_VALUE = true;

export const ANALYSIS_STATUS_VALUES = {
  QUEUED: 'QUEUED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
};

export const ANALYSIS_STATUS_LABELS = {
  [ANALYSIS_STATUS_VALUES.QUEUED]: '대기 중',
  [ANALYSIS_STATUS_VALUES.IN_PROGRESS]: '진행 중',
  [ANALYSIS_STATUS_VALUES.COMPLETED]: '완료',
  [ANALYSIS_STATUS_VALUES.FAILED]: '실패',
};

export const ANALYSIS_STAGE_VALUES = {
  REPO_LIST: 'REPO_LIST',
  FOLDER_STRUCTURE: 'FOLDER_STRUCTURE',
  FILE_DETAIL: 'FILE_DETAIL',
  SUMMARY: 'SUMMARY',
  QUESTION_GENERATION: 'QUESTION_GENERATION',
};

export const ANALYSIS_STAGE_ORDER = [
  ANALYSIS_STAGE_VALUES.REPO_LIST,
  ANALYSIS_STAGE_VALUES.FOLDER_STRUCTURE,
  ANALYSIS_STAGE_VALUES.FILE_DETAIL,
  ANALYSIS_STAGE_VALUES.SUMMARY,
  ANALYSIS_STAGE_VALUES.QUESTION_GENERATION,
];

export const ANALYSIS_STAGE_LABELS = {
  [ANALYSIS_STAGE_VALUES.REPO_LIST]: '저장소 조회',
  [ANALYSIS_STAGE_VALUES.FOLDER_STRUCTURE]: '폴더 구조 분석',
  [ANALYSIS_STAGE_VALUES.FILE_DETAIL]: '핵심 파일 수집',
  [ANALYSIS_STAGE_VALUES.SUMMARY]: '코드 요약 분석',
  [ANALYSIS_STAGE_VALUES.QUESTION_GENERATION]: '질문 생성',
};

export const TERMINAL_ANALYSIS_STATUS_VALUES = [
  ANALYSIS_STATUS_VALUES.COMPLETED,
  ANALYSIS_STATUS_VALUES.FAILED,
];

export const DEFAULT_ANALYSIS_POLLING_INTERVAL_MS = 3_000;

export const DEFAULT_ANALYSIS_RUN_LIST_PAGE = 1;
export const DEFAULT_ANALYSIS_RUN_LIST_SIZE = 20;

export const DEFAULT_GENERATED_QUESTION_LIST_PAGE = 1;
export const DEFAULT_GENERATED_QUESTION_LIST_SIZE = 20;

export const GENERATED_QUESTION_SORT_VALUES = {
  PRIORITY: 'priority',
  CATEGORY: 'category',
  CREATED_AT: 'created_at',
};

export const GENERATED_QUESTION_ORDER_VALUES = {
  ASC: 'asc',
  DESC: 'desc',
};

export const DEFAULT_GENERATED_QUESTION_SORT =
  GENERATED_QUESTION_SORT_VALUES.PRIORITY;
export const DEFAULT_GENERATED_QUESTION_ORDER =
  GENERATED_QUESTION_ORDER_VALUES.ASC;
